version: "3.7"

services:

  django:
    container_name: opportunity_job-django
    build:
      context: ./opportunity_job_api
      target: development
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./opportunity_job_api/src:/app/src/
      - ./opportunity_job_api/scripts/:/app/scripts/
      - ./opportunity_job_api/requirements:/app/requirements/
    restart: always

  postgres:
    container_name: opportunity_job-postgres
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - opportunity_job-postgres-data:/var/lib/postgresql/data
    restart: always

  nextjs:
    container_name: opportunity_job-nextjs
    ports:
      - "3000:3000"
    build:
      context: ./opportunity_job_app
      target: development
    volumes:
      - ./opportunity_job_app:/usr/app/
    env_file:
      - .env
    restart: always

volumes:
  opportunity_job-postgres-data:
