[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "opportunity_job_api.settings"

[tool.coverage.html]
directory = "static/coverage"

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "class TestCase",
]

# flake8 doesn't support pyproject.toml file configuration but
# Flake8-pyproject (https://github.com/john-hen/Flake8-pyproject)
# adds that support to flake8
[tool.flake8]
plugins = "quotes"
inline-quotes = "double"
max-line-length = 120
exclude = "*/migrations/,opportunity_job_api/settings/__init__.py"
per-file-ignores = ["__init__.py:F401"]
ignore = ["E203", "W503"]

[tool.isort]
profile = "black"
