from apps.users.views.applicant_registration_api_view import RegisterApplicantAPIView
from apps.users.views.login_api_view import LoginAPIView
from apps.users.views.statistics_api_view import StatisticsAPIView
