# Generated by Django 4.2.6 on 2023-10-14 13:13

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_applicantaccount_education_and_more'),
        ('jobs', '0004_joboffer_required_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('applicant_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.applicantaccount')),
                ('job_offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.joboffer')),
            ],
            options={
                'verbose_name': 'Job Enrollment',
                'verbose_name_plural': 'Job Enrollments',
            },
        ),
    ]
