# Generated by Django 4.2.6 on 2023-10-14 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_applicantaccount_education_and_more'),
        ('jobs', '0006_alter_jobenrollment_applicant_account_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobenrollment',
            unique_together={('job_offer', 'applicant_account')},
        ),
    ]
