# Generated by Django 4.2.6 on 2023-10-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobenrollment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joboffer',
            name='additional_skills',
            field=models.CharField(blank=True, max_length=250, verbose_name='additional skills'),
        ),
    ]
