# Generated by Django 4.2.6 on 2023-10-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_joboffer_additional_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='additional_skills_en',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='additional skills'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='additional_skills_sr_latn',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='additional skills'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='job_description_en',
            field=models.TextField(null=True, verbose_name='job description'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='job_description_sr_latn',
            field=models.TextField(null=True, verbose_name='job description'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='job_name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='job name'),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='job_name_sr_latn',
            field=models.CharField(max_length=250, null=True, verbose_name='job name'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='category',
            field=models.CharField(choices=[('sales_and_trade', 'Sales and Trade'), ('tourism_and_catering', 'Tourism and Catering'), ('transport_and_logistics', 'Transport and Logistics'), ('cleaning_and_maintenance', 'Cleaning nad Maintenance'), ('production_jobs', 'Jobs in production industry'), ('food_technology', 'Food technology'), ('beauty_care', 'Beauty Care'), ('other', 'Other')], default='other', max_length=30, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='engagement',
            field=models.CharField(choices=[('course', 'Course or internship'), ('unpaid_internship', 'Unpaid internship'), ('paid_internship', 'Paid internship'), ('part_time', 'Part time job offer'), ('full_time', 'Full time job offer')], default='full_time', max_length=20, verbose_name='engagement'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='required_education',
            field=models.CharField(choices=[('none', 'No formal education'), ('first_degree', 'First degree, 4 years of primary school'), ('second_degree', 'Second degree, primary school'), ('third_degree', 'Third degree, high school'), ('fourth_degree', 'Fourth degree, high school'), ('fifth_degree', 'Fifth degree, highly qualified, high school'), ('sixth_degree', 'Sixth degree, higher education, high school'), ('seventh_degree', 'Seventh degree, higher vocational education, higher education school')], default='none', max_length=20, verbose_name='required education'),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='required_work_experience',
            field=models.CharField(choices=[('none', 'No work experience'), ('lt_year', 'Less than a year'), ('one_to_three', 'More than one less than three years'), ('three_to_five', 'More than three less than five years'), ('five_to_ten', 'More than five less than ten years'), ('gt_ten', 'More than ten years')], default='none', max_length=20, verbose_name='required work experience'),
        ),
    ]
