# Generated by Django 4.2.6 on 2023-10-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_joboffer_additional_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobenrollment',
            name='is_pending',
            field=models.BooleanField(default=True, verbose_name='pending?'),
        ),
    ]
