# Generated by Django 4.2.6 on 2023-11-01 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_jobenrollment_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobenrollment',
            name='is_pending',
            field=models.BooleanField(default=True, help_text='The status indicates whether the enrollment has been processed. If the status is pending, the applicant either needs to connect with the employer to complete the application process, or someone else may need to apply for the job on behalf of the applicant.', verbose_name='pending?'),
        ),
    ]
