# Generated by Django 4.2.6 on 2023-10-14 06:47

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('applicant', 'Applicant'), ('employer', 'Employer')], default='applicant', max_length=9, verbose_name='account_type'),
        ),
        migrations.CreateModel(
            name='EmployerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('company_name', models.CharField(max_length=250, verbose_name='company name')),
                ('pib', models.CharField(max_length=8, verbose_name='PIB')),
                ('address', models.CharField(max_length=250, verbose_name='company address')),
                ('phone_number', models.CharField(max_length=30, verbose_name='company phone number')),
                ('url', models.URLField(verbose_name='company url')),
                ('about', models.TextField(max_length=500, verbose_name='about company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Employer Account',
                'verbose_name_plural': 'Employer Accounts',
            },
        ),
        migrations.CreateModel(
            name='ApplicantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('first_name', models.CharField(max_length=250, verbose_name='first name')),
                ('last_name', models.CharField(max_length=250, verbose_name='last name')),
                ('work_experience', models.CharField(choices=[('none', 'No work experience'), ('lt_year', 'Less than a year'), ('one_to_three', 'More than one less than three'), ('three_to_five', 'More than three less than five'), ('five_to_ten', 'More than five less than ten'), ('gt_ten', 'More than ten')], default='none', help_text='Work experience of the applicant', max_length=14, verbose_name='work experience')),
                ('education', models.CharField(choices=[('none', 'No formal education'), ('first_degree', 'First degree, 4 years of primary school'), ('second_degree', 'Primary school'), ('third_degree', 'High school'), ('fourth_degree', 'High school'), ('fifth_degree', 'High school'), ('sixth_degree', 'VSS'), ('seventh_degree', 'VSS')], default='none', help_text='Education of the applicant', max_length=14, verbose_name='education level')),
                ('about', models.TextField(blank=True, max_length=500, null=True, verbose_name='about me')),
                ('cv', models.FileField(blank=True, default=None, upload_to='uploads/users/applicant_account/', validators=[])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Applicant Account',
                'verbose_name_plural': 'Applicant Accounts',
            },
        ),
    ]
