# Generated by Django 4.2.6 on 2023-10-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_applicantaccount_about_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeraccount',
            name='pib',
            field=models.IntegerField(help_text='In Serbia, this number contains 9 numeric characters', verbose_name='PIB'),
        ),
    ]
