# Generated by Django 4.2.6 on 2023-10-31 03:51

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_employeraccount_pib'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('subject', models.CharField(max_length=250, verbose_name='email subject')),
                ('subject_en', models.CharField(max_length=250, null=True, verbose_name='email subject')),
                ('subject_sr_latn', models.CharField(max_length=250, null=True, verbose_name='email subject')),
                ('context', models.JSONField(default=dict, verbose_name='email context')),
                ('template_path', models.CharField(max_length=250, verbose_name='template path')),
                ('category', models.CharField(default='general', help_text='For easier grouping and searching of specific emails', max_length=250, verbose_name='category')),
                ('status', models.CharField(choices=[('pending', 'waiting to send email'), ('success', 'successfully sent email'), ('failure', 'failed to send email')], default='pending', help_text='Note that the email can successfully be sent even if the recipient email address does not exist', max_length=10, verbose_name='status')),
                ('error', models.TextField(default='', help_text='An error occurred during the email sending process', verbose_name='error')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Password Reset Email',
                'verbose_name_plural': 'Password Reset Emails',
            },
        ),
    ]
