# Generated by Django 4.2.4 on 2023-09-30 06:16

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('subject', models.CharField(max_length=250, verbose_name='email subject')),
                ('recipient', models.CharField(max_length=250, verbose_name='recipient email address')),
                ('context', models.JSONField(default=dict, verbose_name='email context')),
                ('template_path', models.CharField(max_length=250, verbose_name='template path')),
                ('category', models.CharField(default='general', help_text='For easier grouping and searching of specific emails', max_length=250, verbose_name='category')),
                ('status', models.CharField(choices=[('pending', 'waiting to send email'), ('success', 'successfully sent email'), ('failure', 'failed to send email')], default='pending', help_text='Note that the email can successfully be sent even if the recipient email address does not exist', max_length=10, verbose_name='status')),
                ('error', models.TextField(default='', help_text='An error occurred during the email sending process', verbose_name='error')),
            ],
            options={
                'verbose_name': 'Email Thread',
                'verbose_name_plural': 'Email Threads',
            },
        ),
    ]
