# Generated by Django 4.2.6 on 2023-10-31 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_email_subject_en_email_subject_sr_latn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
